### ISSUE TITLE
Crash on requiring bundled gems

### ISSUE THREAD

**Issue by pbosetti** [mattn/mruby-require#23]
On requiring a bundled gem, I get the following crash, whichever is the gem I require:
```ruby
> require 'mruby-complex'
mirb(13889,0x7fff7df1f300) malloc: *** error for object 0x10066cc30: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

This happens for both C-compiled gems as well as pure ruby gems. Conversely, requiring plain ruby files and bytecode compiled files (`.mrb`) works as expected.

**Comment by mattn** [comment]
Hmm, I couldn't repro.

![](http://go-gyazo.appspot.com/a0d14804c5973251.png)

**Comment by pbosetti** [comment]
In fact, I didn't test that mruby-curl gem 😉. Until now that is the only one working. If you try your mruby-pcre-regexp I am pretty sure you'll get the crash.
Note that we have a crash also for plain ruby gems, as `pbosetti/mruby-complex`.
I get same crashes on Debian Wheezy and Mac OS X (10.10), on clang and gcc.
For reference, I can replicate it on travis-ci, and I have a branch in my fork that enables the travis-ci. Should I PR?

**Comment by pbosetti** [comment]
We probably found the problem: any gem having a non-empty `mrblib` folder (i.e. compiling bytecode) crashes. For example, if you remove the `pcre_regexp.rb` from mattn/mruby-pcre-regexp, that gem can be loaded (although of course it doesn't work).

**Comment by pbosetti** [comment]
Update: crash happens at line 354 of mob_require.c, when doing `mrb_load_irep_data()`.

**Comment by mattn** [comment]
Is this same result? https://travis-ci.org/mattn/mruby-require/jobs/52262889

**Comment by pbosetti** [comment]
It is similar: https://travis-ci.org/pbosetti/mruby-emb-require/jobs/52256174

**Comment by pbosetti** [comment]
Another update following the flow: is at line 232 when doing `mrb_realloc()`

**Comment by pbosetti** [comment]
Hi @mattn any news on this matter? I've spent a whole day on it and still I could not fix.

**Comment by mattn** [comment]
https://travis-ci.org/mattn/mruby-require/jobs/54360444 :metal:
